#!/usr/bin/env bash

set -e

sudo pacman -S --noconfirm --needed \
  adobe-source-han-sans-otc-fonts \
  bat \
  cmake \
  exa \
  firefox-developer-edition \
  fuse \
  fzf \
  git \
  gnome-keyring \
  gwenview \
  hdparm \
  inter-font \
  linux-zen \
  man \
  ninja \
  noto-fonts-cjk \
  noto-fonts-emoji \
  python python-pip \
  ripgrep \
  rsync \
  tree-sitter \
  unzip zip \
  vi \
  wget \
  wl-clipboard \
  zsh

# This changes the default shell to zsh.
if [[ ! $(basename "$SHELL") == 'zsh' ]]
then
  chsh -s /bin/zsh "$USER"
fi
