#!/usr/bin/env bash

# Install and configure rustup if the binary is not found
if [[ ! $(command -v rustup) ]]
then
  sudo pacman -S rustup
  rustup default stable
  rustup self upgrade-data
fi

git clone --depth=1 https://aur.archlinux.org/paru.git
cd paru || exit
makepkg -si
