FROM registry.opensuse.org/opensuse/distrobox-packaging:latest

LABEL maintainer="santiagogonzalezbogado@gmail.com"
LABEL version="0.0.6"
LABEL description="Main container for the maintainer"

RUN zypper --non-interactive update

RUN zypper --non-interactive install -y \
  ShellCheck \
  autoconf \
  automake \
  cmake \
  curl \
  ffmpeg-4 \
  flatpak \
  flatpak-spawn \
  flatpak-xdg-utils \
  fuse \
  fuse-devel \
  fzf \
  fzf-zsh-completion \
  gawk \
  gcc \
  gcc-c++ \
  gettext-tools \
  git \
  go \
  gzip \
  jq \
  kde-cli-tools5 \
  libnotify-tools \
  libopenssl-devel \
  libtool \
  make \
  ninja \
  password-store \
  python \
  rsync \
  tar \
  tree-sitter \
  unzip \
  wl-clipboard \
  xdg-desktop-portal \
  xdg-desktop-portal-gtk \
  xdg-desktop-portal-kde \
  xdg-menu \
  xdg-user-dirs \
  xdg-user-dirs-gtk \
  xdg-utils \
  yt-dlp \
  zip \
  zsh \
  zstd

RUN zypper clean

RUN ln -s /usr/bin/distrobox-host-exec /usr/local/bin/podman
RUN ln -s /usr/bin/distrobox-host-exec /usr/bin/distrobox

# chsh -s /bin/zsh
CMD /bin/zsh
