FROM docker.io/library/archlinux:base-devel

# main-distrobox is a WIP, hopefully I'll not be using distrobox in the future
# and I'll just use podman alone like in:
# https://github.com/akdev1l/devenv
# https://github.com/akdev1l/etbox

LABEL maintainer="santiagogonzalezbogado@gmail.com"
LABEL version="0.0.3"
LABEL description="Main container for the maintainer"

RUN pacman -Syyuu --noconfirm
RUN pacman -S --noconfirm \
  bat \
  cmake \
  exa \
  fzf \
  git \
  luacheck \
  make \
  man \
  ninja \
  pass \
  python \
  python-pip \
  ripgrep \
  rsync \
  shellcheck \
  tree-sitter \
  unzip zip \
  vi \
  wget \
  wl-clipboard \
  zsh

RUN usermod -s /bin/zsh root
RUN chsh -s /bin/zsh root

CMD /bin/bash
