---
- name: remove or hide packages from base image
  community.general.rpm_ostree_pkg:
    state: absent
    name:
      - mesa-va-drivers
      - libavcodec-free
      - libavfilter-free
      - libavformat-free
      - libavutil-free
      - libpostproc-free
      - libswresample-free
      - libswscale-free
      - kwrite
      - toolbox

- name: install packages with rpm-ostree
  community.general.rpm_ostree_pkg:
    state: present
    name:
      - distrobox
      - ffmpeg
      - ffmpegthumbs
      - intel-media-driver
      - mesa-va-drivers-freeworld
