# ARG SOURCE_IMAGE
# ARG FEDORA_MAJOR_VERSION
# FROM ${SOURCE_IMAGE}:${FEDORA_MAJOR_VERSION}
FROM kinoite:39

COPY playbooks /tmp
RUN rpm-ostree install -y ansible
RUN ansible-galaxy install -r /tmp/requirements.yml
RUN ansible-playbook /tmp/entrypoint.yml

RUN rm -rf ~/.ansible /var/* ~/.*
RUN rpm-ostree cleanup -m

RUN ostree container commit
