---
- name: Post install configs
  hosts: localhost
  tasks:
    - import_tasks: ./tasks/flatpak-auto-update.yml
    - import_tasks: ./tasks/flatpak-packages.yml
    - import_tasks: ./tasks/rpm-ostree-service.yml
  handlers:
    - name: Reload user systemd services
      systemd:
        name: --user
        state: reloaded
