FROM kinoite:39

COPY playbooks/install /tmp
RUN rpm-ostree install -y ansible
RUN ansible-galaxy install -r /tmp/requirements.yml
RUN ansible-playbook /tmp/entrypoint.yml

RUN rm -rf ~/.ansible /var/* ~/.*
RUN rpm-ostree cleanup -m

RUN ostree container commit
